import com.android.build.api.dsl.LibraryExtension

plugins {
    alias(libs.plugins.android.library)
}

LibraryExtension getLibraryExt() {
    return getExtensions().findByType(LibraryExtension.class)
}

configure(getLibraryExt()) {
    namespace 'org.fk.hidden'
    compileSdk = 37

    defaultConfig {
        minSdk 24
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {}
