import com.android.build.api.dsl.ApplicationExtension

plugins {
    alias(libs.plugins.android.application)
}

final var localProperties = new Properties()
final var localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localProperties.load(localPropertiesFile.newInputStream())
}

ApplicationExtension getAppExt() {
    return getExtensions().findByType(ApplicationExtension.class)
}

base {
    archivesName = "${rootProject.name.replace(" ", "_")}-v${getAppExt().defaultConfig.versionName}"
}

configure(getAppExt()) {
    namespace 'com.fk.smartpixelsposed'
    compileSdk = 37

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId = namespace
        minSdk = 24
        targetSdk = compileSdk
        versionCode = 15
        versionName = "1.15"
        multiDexEnabled = false
    }

    signingConfigs {
        final var fileDir = localProperties.getProperty("fileDir")
        if (fileDir != null) {
            release {
                storeFile = file(fileDir)
                storePassword = localProperties.getProperty("storePassword")
                keyAlias = localProperties.getProperty("keyAlias")
                keyPassword = localProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            if (localProperties.getProperty("fileDir") != null) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    //noinspection GradleDependency
    compileOnly libs.xposedapi
    compileOnly project(':hidden')
}
